Add 'VHDL_LIB_ORDER' to specify VHDL library ordering (#2635)
A regression test has been added to make sure we can now compile
multiple libraries. With four libraries the chance of a false positive
should be 1/4 * 1/3 * 1/2 ~ 4%.

Note that the logic sanity checking VHDL_LIB_ORDER and VHDL_SOURCES_*
has quadratic complexity, although it has been checked to perform within
bounds for at least 25 libraries.

Closes #2633

diff --git a/cocotb/share/makefiles/Makefile.inc b/cocotb/share/makefiles/Makefile.inc
--- a/cocotb/share/makefiles/Makefile.inc
+++ b/cocotb/share/makefiles/Makefile.inc
@@ -150,6 +150,20 @@ endif
 
 export LIBPYTHON_LOC
 
+define check_vhdl_sources
+if [ "$(VHDL_SOURCES_$(LIB))" == "" ]; then \
+  >&2 echo "ERROR: VHDL_SOURCES_$(LIB) is empty or undefined, but '$(LIB)' is present in VHDL_LIB_ORDER."; \
+  exit 1; \
+fi;
+endef
+
+define check_lib_order
+  if [ "$(filter $(SOURCES_VAR:VHDL_SOURCES_%=%), $(VHDL_LIB_ORDER))" == "" ]; then \
+    >&2 echo "ERROR: $(SOURCES_VAR) defined, but library $(SOURCES_VAR:VHDL_SOURCES_%=%) not present in VHDL_LIB_ORDER."; \
+    exit 1; \
+  fi;
+endef
+
 else
     $(warning Including Makefile.inc from a user makefile is a no-op and deprecated. Remove the Makefile.inc inclusion from your makefile, and only leave the Makefile.sim include.)
 endif # COCOTB_MAKEFILE_INC_INCLUDED
